### ISSUE TITLE
Assign to nonlocal __class__ variable in instance method causes stack overflow

### ISSUE THREAD

**Issue by isaiah** [IronLanguages/ironpython3#1085]
```python
class A():
    def f(self):
        nonlocal __class__
        __class__ = A

if __name__ == '__main__':
    A().f()
```
Execute the script will result in
```
Stack overflow.
Repeat 174476 times:
--------------------------------
   at IronPython.Compiler.Ast.PythonReferenceVariable.get_LimitVariable()
--------------------------------
   at IronPython.Compiler.Ast.ScopeStatement.GetVariableExpression(IronPython.Compiler.Ast.PythonVariable)
   at IronPython.Compiler.Ast.FunctionDefinition.CreateFunctionLambda()
   at IronPython.Compiler.Ast.FunctionDefinition.EnsureFunctionLambda()
   at IronPython.Compiler.Ast.FunctionDefinition.GetLambda()
...
```

This also causes the `CPython.test_super` test to crash.

**Comment by BCSharp** [comment]
The current implementation of `__class__` is a hack (see #721, #723) that does fail in some not so straightforward cases. There has been one attempt on a proper implementation (#734), so far unsuccessful. I looked into it too, several weeks ago, and I believe I was on the right track but I run out of time before I could finish it. Perhaps I should have commited the unfinished works anyway, if not to just contribute to the discussion about a proper solution.

**Comment by isaiah** [comment]
Thanks for pointing the direction. AFAIK, cpython generates a new scope to encapsulate the `__class__` cell when either `super` or `__class__` is found in the class body. The solution proposed by #734 doesn't really scale, as it assumes the class scope is the grand parent. If you don't mind, maybe you can share your work and I can try to pick it up?

**Comment by BCSharp** [comment]
The idea I had been pursuing was based on an observation that in CPython, `__class__` used within the class scope and all nested scopes (like member methods) behaves like an ordinary variable that just happen to be initialized with the value of the class type. This is remarkably different than the `__class__` **attribute** on the same type. For instance, you can assign anything to the former, while with the latter only values of a workable type are accepted. Whether this is intentional or not, I don't know, but this is how it works in CPython.

So the solution was to introduce an extra variable `ClassVariable` in `ClassDefinition`, initialized with name `__class__` and value the type of the class; almost identical to the currently existing `PythonVariable` (which also exists in `FunctionDefinition`), ecxept that `ClassVariable` lives in the class scope while `PythonVariable` in the parent scope and represents the actual class name.

The existing name binding algorithm was taking care of all the rest without any modification.

What was not working is proper ordering of class type definition and the variable initialization, probably due to an overly aggressive performance optimization in `ClassDefinition`. As a result, the variable was being accessed before it it was being set.

Hopefully I will find some time in the coming few days to review and cleanup the code and make a commit.

**Comment by BCSharp** [comment]
See #1086.
