### ISSUE TITLE
No Module Named Pipes

### ISSUE THREAD

**Issue by Cx01N** [IronLanguages/ironpython3#1388]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [X] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description
Unable to import System.IO.Pipes.

### Steps to Reproduce

1.  Start IronPython console
2. import System.IO.Pipes

**Expected behavior:** [What you expected to happen]
System.IO.Pipes be imported.

**Actual behavior:** [What actually happened]
No module named Pipes is found.

### Versions
3.4

You can get this information from executing `ipy -V`.
3.4.0.0001

**Comment by BCSharp** [comment]
Did you add a reference to the assembly containing the types in this namespace?

E.g.:

```pycon
>>> import System.IO.Pipes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Pipes
>>> import clr
>>> clr.AddReference('System.Core')
>>> import System.IO.Pipes
>>> int(System.IO.Pipes.PipeAccessRights.FullControl)
2032031
```

**Comment by Cx01N** [comment]
Oh I didn't try that. import System.IO worked for all the other System.IO classes that I was using without needing to import System.Core first. Is there a reason Pipes is different?

**Comment by BCSharp** [comment]
The other classes you were trying to import are defined in `mscorlib.dll`, which is always automatically referenced as it contains all fundamental .NET types.

Classes in `System.IO.Pipes` are defined in a separate assembly. On .NET Framework, it is `System.Core.dll`, and on .NET/.NET Core it is `System.IO.Pipes.dll`. You can also add a reference to `System.Core.dll` on .NET/.NET Core and it will work because that assembly is just a type forwarder to the actual assembly implementing the type.

In general, if wondering which assembly contains a type you are interested in, go to .NET API browser, look up the type, e.g. [AnonymousPipeClientStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.anonymouspipeclientstream?view=net-6.0), make sure you have selected the .NET version you are interested in, and look for section **Definition**.  The assembly is listed right under the namespace.

**Comment by Cx01N** [comment]
Thanks for the great explanation, that makes a lot more sense now.
