### ISSUE TITLE
.NET Overloads appearing in dir(0)

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#1395]
Some of the .NET Overloads are now appearing in `dir(0)`:
>['CompareTo', 'Equals', 'GetHashCode', 'GetTypeCode', 'MaxValue', 'MinValue', 'Parse', 'ToBigInteger', 'ToBoolean', 'ToByte', 'ToChar', 'ToDateTime', 'ToDecimal', 'ToDouble', 'ToInt16', 'ToInt32', 'ToInt64', 'ToSByte', 'ToSingle', 'ToString', 'ToType', 'ToUInt16', 'ToUInt32', 'ToUInt64', 'TryParse', ...]

Expected behaviour is to not see them until someone steps out of the Python world (e.g. via `import System`).

@BCSharp I guess this is related to some of the recent `int` changes?

**Comment by BCSharp** [comment]
I have it on my to-do list. The issue exists because now `Int32` does not fit in the dichotomy _Python type_ vs. _non-Python type_, which the `PythonType`/`PythonTypeOps` mechanisms support.

Ideally, I'd hide .NET members on `Int32` instances (until `import System`) but not on the actual `Int32` type. Such a distinction is not supported by the Python type mechanism and adding it would likely significantly increase the complexity of the code, so I am currently inclined not to go that far. Anyway, I going to submit my changes so far in a draft PR so that we can have a discussion supported by real code. @slozier
