### ISSUE TITLE
MissingMemberException in V3.4.0 beta 

### ISSUE THREAD

**Issue by nalsandori** [IronLanguages/ironpython3#1590]
**# Previously, I had installed IronPython(Ver 2.7.9) in the  c# code and used it**
**# Now, I installed IronPython-3.4.0b1.msi**
**# But, there is an exception when I run c# code below**
`IronPython.Hosting.Python.CreateEngine()`
**Exception Message - System.MissingMemberException(IronPython.dll): 'type' object has no attribute '_ORIGIN'**
**# There was a problem like the above, so I rolled back to version 2.7.9 or 2.7.12**   
**→ It was good working!**
**# Please check the problem.**

**Comment by slozier** [comment]
Where are you seeing this exception? It is from importlib and is caught so it should not cause any problems...

**Comment by nalsandori** [comment]
> Where are you seeing this exception? It is from importlib and is caught so it should not cause any problems...

MissingMemberException is pointing ti IronPython.dll
The exception point is when Python.CreateEngin() is called
I used it well in previous versions(2.7.9)
My program implemented by WPF uses .NET Framework 4.7.2

**Comment by slozier** [comment]
Yes, there is a `MissingMemberException` that occurs inside IronPython.dll when `Python.CreateEngine()` is called, but it is also caught inside IronPython.dll so you can ignore it. I do not understand the issue.

**Comment by nalsandori** [comment]
> Yes, there is a `MissingMemberException` that occurs inside IronPython.dll when `Python.CreateEngine()` is called, but it is also caught inside IronPython.dll so you can ignore it. I do not understand the issue.

All right.
I will ignore those exceptions.
The reason why i asked this question is that the functikn associated with the eventhandler is not called when calling print.
`memorystream = new MemoriStream();
outputWr = new EventRaisingStreamWriter(memorystream)
outputWr.StringWritten += new EventHandler<MyEvtArgs<stribg>>(pythonOutput_Written);
engine = Python.CreateEngin()
engine.Runtime.IO.SetOutput(memoryStream, outputWr);
engine.Runtime.IO.SetErrorOutput(memoryStream, outputWr);`
I'll look further into thrle issue of events not being invoked.
If you have any advice on this issue, plz
Ah, when I import logging library, there are so many exception.
Can i ignore this message, too?
I wish you all the best

**Comment by slozier** [comment]
I assume you are referring to the `KeyNotFoundException` exceptions? Unfortunately throwing and catching exceptions is expected behavior for Python so those are normal. They are thrown (and caught) by `importlib` so you can ignore them. I will see if I can modify `importlib` to avoid throwing and catching some exceptions but it may not be possible in all cases. You could try using the old import mechanism to reduce the number of thrown/caught exceptions (but the option may be removed in the future):
```C#
Python.CreateEngine(new Dictionary<string, object> { { "NoImportLib", true } });
```

In a previous message you mentioned something about trying to use `engine.Runtime.IO.SetOutput`, unfortunately calling this with a `TextWriter` will no longer work since Python 3 only prints to a binary stream. See https://github.com/IronLanguages/ironpython3/issues/1204 for details.
