### ISSUE TITLE
Lookuperror: unknown encoding: cp949

### ISSUE THREAD

**Issue by nalsandori** [IronLanguages/ironpython3#1768]
- I installed Ironpython V3.4.1 on windows10, which is based on Korean.
- Then, the following command was executed on the IronPython Console.
- 『cp949』 items were printed in the results performed.
- However, if the same command is executed in my program implemented in c#, only the 『cp949』 item is missing.

![image](https://github.com/IronLanguages/ironpython3/assets/22561769/1a4bbe26-1d33-45ae-9f1d-28bec997c721)

- If I run the code below, the console will perform in normally.
`with open(path, 'r') as f:
	content = f.read()		#problem line`
- But, the following error occurs in my program developed with c#. 
  > Lookuperror: unknown encoding: cp949
- Is the reason for this problem related to the above?

**Comment by slozier** [comment]
The command line and C# program could have different default encodings. What value does `f.encoding` give you?

Is your file really using the `cp949` encoding? If not you could pass in an explicit encoding, for example if it's `utf-8`: `open(path, 'r', encoding='utf-8')`.

`cp949` is not available because we don't have an implementation for `_codecs_kr`. Related issue: https://github.com/IronLanguages/ironpython2/issues/659

**Comment by nalsandori** [comment]
> I excuted the following commands in each program respectively.
`>>>sys.getdefaultencodnig()`  --> 'utf_8'

> The same results were displayed on both the ironpython console and c# program

> The following code also causes an encoding error in c# program(based on ironpython 3.4.1)
`os.popen(uabswitchcmdpath + ' -v').read()`
  --> the above command worked fine in a c# program based on ironpython 2.7.9

> Here is the c# initialize code
`var r = IronPython.Hosting.Python.CreateRuntime();
runtime.IO.SetErrorOutput(streamwriter, Encoding.Default);
runtime.IO.SetOutput(streamwriter, Encoding.Default);
`runtime.IO.SetInput(streamwriter, Encoding.Default);

**Comment by nalsandori** [comment]
Thank you very much for your kind explanation.
The c# code has been helpful to me
