### ISSUE TITLE
PEP 3115 -- Metaclasses in Python 3000

### ISSUE THREAD

**Issue by jdhardy** [IronLanguages/ironpython3#20]
http://www.python.org/dev/peps/pep-3115/

**Comment by moto-timo** [comment]
Initial CPython implementation: https://hg.python.org/cpython/rev/19f7ff443718

**Comment by moto-timo** [comment]
Very early beginnings of implementation: https://github.com/moto-timo/ironpython3/tree/pep-3115-metaclass-syntax

**Comment by moto-timo** [comment]
Getting closer: https://github.com/moto-timo/ironpython3/tree/pep-3115

**Comment by slozier** [comment]
Revert https://github.com/IronLanguages/ironpython3/pull/169 hack once this is properly implemented.

**Comment by BCSharp** [comment]
[Originally](https://github.com/IronLanguages/ironpython3/issues/1208#issuecomment-834757250) I intended to remove `__classcell__` and replace it with an extra parameter to `PythonOps.MakeClass`, but since Python 3.6 introduces it and IronPython 3.4 already implements a number of Python 3.6 behaviour, it is probably not worth it.  Instead of it, I plan now to implement the Python 3.6 behaviour fully.

There are two significant changes in Python [3.6](https://docs.python.org/3.6/reference/datamodel.html#creating-the-class-object) WRT [3.4](https://docs.python.org/3.4/reference/datamodel.html#creating-the-class-object) related to handling of `__class__`:

> **CPython implementation detail:** In CPython 3.6 and later, the `__class__` cell is passed to the metaclass as a `__classcell__` entry in the class namespace. If present, this must be propagated up to the `type.__new__` call in order for the class to be initialised correctly. Failing to do so will result in a [DeprecationWarning](https://docs.python.org/3.6/library/exceptions.html#DeprecationWarning) in Python 3.6, and a [RuntimeError](https://docs.python.org/3.6/library/exceptions.html#RuntimeError) in Python 3.8.

And:

> When a new class is created by `type.__new__`, the object provided as the namespace parameter is copied to a new ordered mapping and the original object is discarded. The new copy is wrapped in a read-only proxy, which becomes the [__dict__](https://docs.python.org/3.6/library/stdtypes.html#object.__dict__) attribute of the class object.

At the second step `__classcell__` is filtered out rather than deleted from the original namespace dict.

So here is my revised plan:

- [ ] ~Remove `__classcell__` or at least do not use classdict to pass it around (doesn't work well with metaclass `__prepare__` anyway, which may even not support deletion of attributes).~ Implement CPython 3.6 handling of `__classcell__`. I am still debating whether it will be desirable to move the creation of `__classcell__` after the class lambda runs (like CPython does), or is it OK to leave it a the beginning. Not moving will break the code in some pathological cases (like `del __classcell__` in the class body), but moving will require an extra parameter to `MakeClass`, thus increase code complexity.
- [ ] Replace all class variables with class attributes, except `__class__`.
- [ ] Change the class lambda to take its context as parameter, rather than the parent context as it is now. This will require moving of class context creation to outside of the class lambda.
- [ ] Support arbitrary attribute dict type as classdict.
- [ ] Complete implementation of `__prepare__`. At this point, PEP 3115 implementation in WhatsNewInPython30.md can be checked off.
