### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by rogersachan** [IronLanguages/ironpython3#77]

**Comment by slide** [comment]
This is a good tracking issue, thanks for filing it. We would definitely like to support .NET core, we just need to determine if it has everything we need at this point (reflection, il generation, etc)

**Comment by matthiasburger** [comment]
any news or updates here?

**Comment by markusschaber** [comment]
Hi,

On the community meeting yesterday on gitter, it was mentioned that it’s in the works, but most probably, it will need .NET Core 1.1 or 1.2 due to missing APIs in .NET Core 1.0.

Best regards

Markus Schaber

CODESYS® a trademark of 3S-Smart Software Solutions GmbH

Inspiring Automation Solutions
________________________________
3S-Smart Software Solutions GmbH
Dipl.-Inf. Markus Schaber | Product Development Core Technology
Memminger Str. 151 | 87439 Kempten | Germany
Tel. +49-831-54031-979 | Fax +49-831-54031-50

E-Mail: m.schaber@codesys.com<mailto:m.schaber@codesys.com> | Web: codesys.com<http://www.codesys.com> | CODESYS store: store.codesys.com<http://store.codesys.com>
CODESYS forum: forum.codesys.com<http://forum.codesys.com>

Managing Directors: Dipl.Inf. Dieter Hess, Dipl.Inf. Manfred Werner | Trade register: Kempten HRB 6186 | Tax ID No.: DE 167014915
________________________________
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received
this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure
or distribution of the material in this e-mail is strictly forbidden.

**Comment by rogersachan** [comment]
@markusschaber 3 months later .NET Core 1.2 comes closer. Is there any update at this point?

**Comment by markusschaber** [comment]
To be honest, I don't know - I'm not currently working actively on IronPython. :-(

**Comment by slozier** [comment]
@rogersachan I did some work on the IP2.7 branch to try and get it working (and it mostly did) but there are just too many missing APIs with netstandard1.6. We plan to support whatever version of .NET Core implements netstandard2.0.

**Comment by matthiasburger** [comment]
Any plans to get something like a beta release for testing purposes?

**Comment by slide** [comment]
We're still working on all the parser updates and so forth to bring the code in line with CPython 3.x.

**Comment by MrPeKa** [comment]
@slide Is there any assumption about the release date?

**Comment by slide** [comment]
I wish I could give you a date. I think we've realized that there is more than we expected to implement. In addition, we would wait for .NET Standard 2.0

**Comment by MrPeKa** [comment]
So, referring to this - https://github.com/dotnet/core/blob/master/roadmap.md
after spring 2017

**Comment by slozier** [comment]
@pekunicki Like @slide mentioned, given the amount of work left to be done on IronPython 3.0 I don't think we're at a point where we can even guess at a release date. It's more than likely that .NET Standard 2.0 will be ready before IronPython 3.0 in which case the first release will support .NET Core.

**Comment by vivainio** [comment]
@slozier it seems netstandard 2.0 will happen together with VS2017 RTM in march. Is there hope that we could see IronPython 2.7 on Core some time after that?

**Comment by slozier** [comment]
@vivainio Yes, IronPython 2.7 should be no problem, we should have some sort of beta release soon after VS2017 RTM.

**Comment by JoshMcclung** [comment]
@slozier Any update on .Net core suppport now that VS2017 is out?

**Comment by slozier** [comment]
@JoshMcclung We're still waiting for .NET Core 2.0. I had hoped it would come with the VS2017 release but it didn't. Maybe they'll announce something at Build this week?

**Comment by MathiasMagnus** [comment]
FYI: https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/

**Comment by slozier** [comment]
For those interested in helping work out the kinks: https://github.com/IronLanguages/main/pull/1645

**Comment by matthiasburger** [comment]
So .net core 2.0 was released 2 months ago. :) any updates here?

**Comment by gpetrou** [comment]
If you are asking about IronPython2 I assume this will be in the upcoming release.
But @slide can probably confirm that.
If you are asking about IronPython3 I have a pending PR that I need to finish soon.
However, IronPython3 has other items to be done before a release.
I guess if you have time you can contribute to it as well.

**Comment by matthiasburger** [comment]
@gpetrou nope I was asking about IronPython3.  Okay, yep, I got time.

**Comment by gpetrou** [comment]
Great! Maybe @slide or @slozier can give you some specific IronPython3 issues to work on.

**Comment by slide** [comment]
I can add some "entry-level" tags to some issues. I'll try and do that today.

**Comment by matthiasburger** [comment]
@slide you already added some tags? can't find any.

**Comment by slide** [comment]
I had a family emergency come up and won't be able to until next week. My apologies.

**Comment by matthiasburger** [comment]
@slide family is most important - best hopes that it's not too serious!

**Comment by gpetrou** [comment]
Should we close this now since the .NET Core changes were merged?
@matthiasburger there are some issues you can take a look at in https://github.com/IronLanguages/ironpython3/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by slide** [comment]
.NET core support has been merged.
