### ISSUE TITLE
Name fails to resolve in generator's if when inside comprehension

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#817]
The following fails:
```Python
{i: tuple(j for j in t if i != j) for t in ((1,2),) for i in t}
```
with
> NameError: global name 'i' is not defined

Causes `import sre_compile` to fail.

Workaround is to use a comprehension instead of a generator:
```Python
{i: tuple([j for j in t if i != j]) for t in ((1,2),) for i in t}
```

**Comment by slozier** [comment]
Revert https://github.com/IronLanguages/ironpython3/pull/818 once this is fixed.

**Comment by slozier** [comment]
Ran into this again with my own code, something like:
```Python
x = [[1]]
[tuple(y[i] for y in x) for i in range(len(x))]
```

Here's a simpler version:
```Python
[tuple(i for j in [1]) for i in [1]]
```

**Comment by BCSharp** [comment]
It turns out that the way comprehensions are programmed assumes that there will be no other nested scopes in them except other comprehensions. This assumption allows for some simplifications/optimizations/shortcuts, however, it is not true in the general case, as the example with the generator demonstrates. But the problem is not limited to generators. Here is an example with a lambda, which also fails:

```python
[lambda: x for x in [1]][0]()
```

Fixing the problem for the name binding process is fairly simple, and I successfully tried it out. Unfortunately it turns out it only works correctly when run with `ipy` (or `IsolationLevel=PROCESS`). For `IsolationLevel=SCOPE` or `ENGINE`, expression rewriting kicks in and again nested scopes get completely mismanaged. The reason for this is given away in the [doctext](https://github.com/IronLanguages/ironpython3/blob/a16442bef52713627657cb32206199ba7d4f689b/Src/IronPython/Compiler/Ast/Comprehension.cs#L216) on `ComprehensionScope`:

```xml
    /// <summary>
    /// Scope for the comprehension.  Because scopes are usually statements and comprehensions are expressions
    /// this doesn't actually show up in the AST hierarchy and instead hangs off the comprehension expression.
    /// </summary>
```

I see generally two ways forward.

1. Keep patching handling of comprehension scopes, next in lookup rewriting, test, see whether something else fails, paths that, etc. The code will be littered with all kinds of obscure special handling just to make comprehensions work, hopefuly without some unwanted side effects.

2. Reorganize the AST hierarchy, so that sopes may be introduced by both statements and expressions. Since C# does not have multiple inheritance (and all scopes derive from `ScopeStatement`), this would have to be done with an extra interface, say, `IScopeProvider`, and class `Scope` being put completely out of the AST hierarchy. I think this would be neater, but requires quite some change to the code, presumably significantly more than option 1: all current subclasses of `ScopeStatement` (`FunctionDefinition`, `ClassDefinition`, etc.) would need to be factored into a separate definition class and a scope class. These are pieces of some complex code so there is a risk of getting it messed up.

**Comment by slozier** [comment]
Reopening since the issue with scopes is still present:
```C#
var engine = Python.CreateEngine();
var scope = engine.CreateScope();
var source = engine.CreateScriptSourceFromString("assert [lambda: i for i in [1,2]][0]() == 2");
var compiledCode = source.Compile();
compiledCode.Execute(scope);
```
