### ISSUE TITLE
Tests not passing with CPython

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#863]
The following tests are passing with IronPython but failing with CPython 3.4:
- [x] test_bool (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_clrtype (https://github.com/IronLanguages/ironpython3/pull/865)
- [x] test_dict (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_exceptions_generated (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_excinfo (passes with 3.7 and later)
- [x] test_generator (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_kwarg (https://github.com/IronLanguages/ironpython3/pull/865)
- [x] test_memoryview (passes with 3.5 and later)
- [x] test_nonetype (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_regressions (passes with 3.6 and 3.7) (https://github.com/IronLanguages/ironpython3/pull/865)
- [x] test_slots (https://github.com/IronLanguages/ironpython3/pull/865)
- [x] test_specialcontext (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_str (https://github.com/IronLanguages/ironpython3/pull/864)
- [x] test_strformat (https://github.com/IronLanguages/ironpython3/pull/865)
- [x] test_struct (passes with 3.5 and later)
- [ ] test_surrogateescape
- [x] test_traceback (unexpected success - known issue https://github.com/IronLanguages/ironpython3/issues/738)
- [x] test_weakref (https://github.com/IronLanguages/ironpython3/pull/865)

**Comment by slozier** [comment]
@BCSharp the failure with CPython in test_surrogateescape is expected?

**Comment by BCSharp** [comment]
> the failure with CPython in test_surrogateescape is expected?

No, I am surprised by that. In general, I believe that all tests should be passing under CPython 3.4, and any incompatibilities/differences be explicitly handled by `skipUnless` or other conditionals. However, in this case I am surprised by CPython's behaviour, and maybe that's why I have left it like this. There is a possibility this is a CPython's bug, but I haven't investigated it yet.

Are you planning on adding CI checks on tests with CPython, or is it a one-time cleanup action?

**Comment by slozier** [comment]
For the moment it's just a one-time cleanup to identify discrepancies. However if I can get it into a good enough shape for CI it may be worth integrating...
