### ISSUE TITLE
Calling bytes.decode from multiple threads throws a System.InvalidOperationException

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#901]
```Python
import threading

def test_fail():
    def test():
        b"aaa".decode()

    threads = []
    for i in range(5):
        t = threading.Thread(target=test)
        threads.append(t)
        t.start()

    for t in threads:
        t.join()

test_fail()
```
throws
> ValueFactory attempted to access the Value property of this instance

Seems to only occur on .NET Core. Not sure if it's reproducible on every system, but seems consistent on mine. Failure point is when accessing a `Lazy<Encoding>.Value` in `TryGetEncoding`.

It looks like removing the `isThreadSafe: false` from the `Lazy` constructor in `makeEncodingProxy` makes the issue go away, but I'm not sure what the implications of this would be.

@BCSharp

**Comment by BCSharp** [comment]
I was able to reproduce it consistently on .NET Core and Mono on Linux.

This `isThreadSafe: false` is from the time when I replaced `EncodingInfoWrapper` with `Lazy<>` (in ce60c4b939b0cfff91fae9b106ddd87fe7e69896). This was a year ago and I remember that according to .NET Framework documentation `isThreadSafe: false`  (i.e. `LazyThreadSafetyMode.None`) meant that `Lazy` did not guarantee that `Value` would be a singleton, but it was still multi-thread usable. This was exactly what `EncodingInfoWrapper` was providing so an obvious choice as a replacement. I also naïvely assumed that .NET Core is compatible with .NET Framework so never checked its docs. When I now read the documentation, `LazyThreadSafetyMode.None` must not be used in multi-threaded scenarios at all, period. What is strange is that the same text appears now in .NET Framework as well. 

> The Lazy<T> instance is not thread safe; if the instance is accessed from multiple threads, its behavior is undefined. 

So maybe I had misunderstood the behaviour of `Lazy` back then and my memory is providing me false records, or it used to work in .NET Framework but now is discouraged to align with .NET Core. Either way, had I known it was this way, I would have advocated against usage of `Lazy` in `Codecs` cache for performance reasons. 

But having already `Lazy` in place, the next best option is `LazyThreadSafetyMode.PublicationOnly`. Such `Lazy` instance can handle multi-threaded access and the implementation is lighter than `LazyThreadSafetyMode.ExecutionAndPublication`. This is what is done in the recent commit in #900 (582864a1).

However, I am thinking that maybe we can get rid of the whole delayed initialization and the factory lambdas here. It made sense when all `EncodingInfo`s were enumerated, not to instantiate all encodings upfront. But since `EncodingInfo` is not used anymore, the `Codecs` cache can simply cache actual `Encoding` objects, rather than their factories. I am still relying on the `Lazy` behaviour in those few tie/rule-breaking cases of East Asian codecs, but this was a "lazy" approach, since `Lazy` was already there. It can be done differently, without relying on `Lazy`.

**Comment by slozier** [comment]
@BCSharp I think this is resolved?

**Comment by BCSharp** [comment]
The reported issue is resolved, although I sill plan to go ahead with further changes as outlined in my comment above. Perhaps it is best done after factoring out the `IronPython.Runtime.Text` namespace. I have it on my to-do list so I don't need this Issue to remain open.
