### ISSUE TITLE
cp20472 fails to import with a SyntaxError

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#909]
While investigating `EngineTest.ScenarioCodePlex20472` I noticed that `Tests/encoded_files/cp20472.py` does not throw a `SyntaxError` (due to encoding) when importing with CPython (since 3.3). It seems like invalid utf-8 sequences may be acceptable in comments if no encoding is specified?

I don't remember seeing anything documenting this behavior. @BCSharp have you seen anything related to this?

**Comment by BCSharp** [comment]
I have noticed before that CPython hits a different code path when importing files than when running them from the command prompt. This was an (unresolved) challenge when I tried to align IronPython's error handling with CPython, as in IronPython files are loaded the same way regardless whether through import or commadline open. Some of the examples of the discrepacies are reflected in `Tests/modules/io_related/test_codecs` (`test_cp1019`, `test_file_encodings_negative`). Till now I have noticed the differences had been only with the exception message, not an altogether lack of the exception.

My guess would be that the lack of `SyntaxError` when importing `cp20472` with CPython is not intentional since running this file still produces the exception. Perhaps nobody has noticed that before, or cared to fix it since it is a negative case.

**Comment by slozier** [comment]
> My guess would be that the lack of SyntaxError when importing cp20472 with CPython is not intentional since running this file still produces the exception. Perhaps nobody has noticed that before, or cared to fix it since it is a negative case.

Interesting. Since trying to run the file fails with a `SyntaxError` (same error CPython 3.2 throws on import) it seems like it may indeed be a regression with CPython.

I wonder if it's worth adding a test case to check that we indeed fail when trying to import... Otherwise I can just close as won't fix.
