### ISSUE TITLE
pip install fails with SystemError

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#936]
For example, pip installing `pyyaml` fails with:
> SystemError: Parent module 'pkg_resources._vendor.packaging' not loaded, cannot perform relative import

I've attached a "simple" repro of the issue:
[ipy3_import.zip](https://github.com/IronLanguages/ironpython3/files/5111237/ipy3_import.zip)

**Comment by BCSharp** [comment]
Basically, it fails because IronPython is not [using `importlib` as the implementation of `__import__`](https://docs.python.org/3/whatsnew/3.3.html#using-importlib-as-the-implementation-of-import).

For instance, if `test.py` from the zipfile, instead of doing `__import__('extern.packaging.version')`, did `import importlib; importlib.import_module('extern.packaging.version')`, the test works, both under CPython and IronPython.

More specifically, the culprit its the "mysterious hack" in `VendorImporter.load_module` (from `extern/__init__.py`):

```python
                # mysterious hack:
                # Remove the reference to the extant package/module
                # on later Python versions to cause relative imports
                # in the vendor package to resolve the same modules
                # as those going through this importer.
                if sys.version_info > (3, 3):
                    del sys.modules[extant]
```

`VendorImporter` imports its extant `_vendor.packaging` using `__import__`, which places the imported module in `sys.modules` under the module key (`_vendor.packaging`). This is not good enough for `importlib` which expects the module to be accessible under the key based on the original import name `extern.packaging`. So `VendorImporter` reassigns the module in `sys.modules` to the new key. So far, so good. But then, the hack deletes the old key for some reason.

Without this hack, the test works under IronPython as well.

The hack is really mysterious, because it seems totally unnecessary. I tested it with CPython from 3.4 to 3.9, and in no circumstances, the key `_vendor.packaging`, when present, was actually used by `importlib`. However, when not present, it causes IronPython to fail.

I don't have CPython 3.0 - 3.2 to compare, but from the hack comment I gather that the current IronPython behaviour is in line with CPython's import machinery behaviour written in C, which presumably was slightly different than `importlib`. After all, one of the main justification for CPython to switch over to `importlib` was the elimination of subtle incompatibilities.

But now I am confused about the intended future path for IronPython.

On one hand, following CPython, the task to switch over to `importlib` is on the [to-do list for 3.3](https://github.com/IronLanguages/ironpython3/blob/master/WhatsNewInPython33.md#using-importlib-as-the-implementation-of-import).

On the other hand, @slozier [writes](https://github.com/IronLanguages/ironpython3/pull/1060#issuecomment-741047884):

> what really needs to happen is fixing up the import system so we don't need to rely on `importlib` anymore.

So what is it: patching the import machinery in IronPython trying to match `importlib` of follow CPython? After all, CPython's reasons for relying on `importlib` are pretty compelling.

----
A small side note: line 71 in `extern/__init__.py` in the zipped example test:
```python
names = 'packaging'
```
should be
```python
names = 'packaging',
```
but it is further inconsequential for the validity of the test.

**Comment by slozier** [comment]
So the solution would be to inject the the importlib implementation of `__import__` into `__builtins__.__import__` after bootstrapping? Seems fairly straight forward. I'll give it a try...

> So what is it: patching the import machinery in IronPython trying to match importlib of follow CPython? After all, CPython's reasons for relying on importlib are pretty compelling.

I guess what I should have said is we *so we don't need to rely on the current bootstrapping of `importlib` anymore*. Obviously I would prefer to use the importlib mechanism as-is, however the current performance hit on startup is likely unacceptable in the long term.

> But now I am confused about the intended future path for IronPython.

So am I. I don't have any clear ideas about how to get around the performance issue. Some possibilities:
- Beefing up the current implementation to match importlib -- not particularly appealing since we'd have to patch every time CPython changes something.
- Trying to optimize the hot code paths.
- Precompiling the module in a DLL -- this would have been my approach, however the method we previously used to do this was ripped out of .NET Core.
- Magic 😃

**Comment by slozier** [comment]
> So the solution would be to inject the the importlib implementation of __import__ into __builtins__.__import__ after bootstrapping? Seems fairly straight forward. I'll give it a try...

Looks like it's not as simple as that since the import of .NET is not hooked up to the standard import hooks. The correct solution is probably to have a proper importer, but I think I might just hack it for now...

**Comment by BCSharp** [comment]
Trying to match up to `importlib` — across CPython versions, all platforms, fixing bugs and shortcomings in the current `Importer` — is not a very appealing idea. The more we can rely on the existing stdlib pure python implementation, the better. But sometimes it is not easy and/or comes with significant performance, as the codecs example shows.

As an exercise, I have made a modification to `Importer` to match this particular `importlib` behaviour needed to solve this particular issue, I can submit it if you think it will be helpful in the short term. (But installing `pyyaml` still fails, this time because "distutils do not support VC 6.0..."). Though some places in `Importer` made my eyebrows rise...

Longer term, I think that `importlib` is the way, with proper extensions (it is pretty extensible) and optimizations (e.g. eliminate heavy exceptions).

> Precompiling the module in a DLL -- this would have been my approach, however the method we previously used to do this was ripped out of .NET Core.

Precompiling into a DLL sounds like a great idea. What was the method?

**Comment by slozier** [comment]
> As an exercise, I have made a modification to Importer to match this particular importlib behaviour needed to solve this particular issue, I can submit it if you think it will be helpful in the short term.

Might be worth it (in particular if we want to get an alpha out the door).

> But installing pyyaml still fails, this time because "distutils do not support VC 6.0..."

Well, at least that seems like a reasonable failure and not some obscure import issue.

> Precompiling into a DLL sounds like a great idea. What was the method?

You can do it via `ClrModule.CompileModules`. It can be useful for debugging compiled code since you end up with a .NET DLL which you can open up with ILSpy.

**Comment by GeorgeS2019** [comment]
@slozier  instead of creating an issue. 

Question.  Is it feasible to do ipy -m pip install [regex‑2019.2.7‑cp34‑cp34m‑win_amd64.whl from Python Extension Packages for Windows - Christoph Gohlke](https://www.lfd.uci.edu/~gohlke/pythonlibs/)

**Comment by slozier** [comment]
@GeorgeS2019 All those windows binaries are C extension modules which won't work with IronPython.

**Comment by GeorgeS2019** [comment]
@slozier  do you have a long term plan to make C extensions (e.g. numpy etc. ) work?

**Comment by GeorgeS2019** [comment]
@slozier  Here is the [link ](https://github.com/jacks-bush/ironpkg_installer/issues/1#issue-1105173698)(up-to-date to 2019) of Ironclad for Ironpython2. Perhaps you could gather interest from users here. I believe many would like to see that works for Ironpython3 eventually.
