### ISSUE TITLE
sys.int_info is missing

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython3#974]
Not sure what the values should be, probably simplest to match CPython?
```Python
sys.int_info(bits_per_digit=30, sizeof_digit=4)
```

**Comment by dc366** [comment]
Python2 previously had a similar tuple `sys.long_info`, which is implemented as `sys.long_info(bits_per_digit=32, sizeof_digit=4)` in IronPython. It would be a trivial change to change the name to `sys.int_info`, since `sys.long_info` was removed in Python3.

The correct value is more interesting. `bits_per_digit` is either 15 or 30 in CPython and baked in at compile time. Should ipy report its truth (32), or try to match CPython's behavior? `bits_per_digit` appears to be strictly used by CPython in its implementation.

https://github.com/python/cpython/blob/865e4b4f630e2ae91e61239258abb58b488f1d65/Include/longintrepr.h#L9

**Comment by slozier** [comment]
> It would be a trivial change to change the name to sys.int_info, since sys.long_info was removed in Python3.

Ah interesting, I hadn't noticed the `long_info` defined in `sys`. I guess renaming it is the way to go.

> Should ipy report its truth (32), or try to match CPython's behavior?

Either way is fine with me. Might as well go with the truth and amend the standard library tests accordingly. For example, PyPy does the following in its `test_sys`:
```Python
        if test.support.check_impl_detail(cpython=True):
            self.assertTrue(sys.int_info.bits_per_digit % 5 == 0)
        else:
            self.assertTrue(sys.int_info.bits_per_digit >= 1)
```
